server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: notification-service

springdoc:
  api-docs:
    path: /notifications/v3/api-docs
  swagger-ui:
    path: /notifications/swagger-ui.html
    operations-sorter: alpha


logbook:
  format:
    style: http
  filter:
    enabled: true
  predicate:
    exclude:
      - path: /actuator/**
      - path: /favicon.ico

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.zalando.logbook.Logbook: TRACE

management:
  endpoints:
    web:
      base-path: /notifications/actuator
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
