server:
  port: 8082

spring:
  application:
    name: plant-service

# External API Keys from .env
openai:
  api:
    key: ${OPENAI_API_KEY:?OpenAI Key is missing}

plantnet:
  api:
    key: ${PLANTNET_API_KEY:?PlantNet Key is missing}

logging:
  level:
    root: INFO
