server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: plant-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

openai:
  api:
    key: ${OPENAI_API_KEY:?OpenAI Key is missing}

firebase:
  storage-bucket: sprouty-plantapp.firebasestorage.app

plantnet:
  api:
    key: ${PLANTNET_API_KEY:?PlantNet Key is missing}

logbook:
  format:
    style: http
  filter:
    enabled: true
  predicate:
    exclude:
      - path: /actuator/**
      - path: /favicon.ico

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.zalando.logbook.Logbook: TRACE

management:
  endpoints:
    web:
      base-path: /plants/actuator
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
