server:
  port: 8081

spring:
  application:
    name: user-service
  main:
    cloud-platform: "KUBERNETES"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    use-root-path: true

jwt:
  secret: ${JWT_SECRET:?JWT secret is missing}

logbook:
  format:
    style: http
  filter:
    enabled: true
  predicate:
    exclude:
      - path: /actuator/**
      - path: /favicon.ico
      - path: /health
      - path: /metrics

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.zalando.logbook.Logbook: TRACE

management:
  endpoints:
    web:
      base-path: /users/actuator
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always