server:
  port: 8081

spring:
  application:
    name: user-service

jwt:
  secret: ${JWT_SECRET:?JWT secret is missing}

logbook:
  format:
    style: http
  filter:
    enabled: true
  predicate:
    exclude:
      - path: /actuator/**
      - path: /favicon.ico
      - path: /health
      - path: /metrics

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    # This is the "magic" line to make it actually print
    org.zalando.logbook.Logbook: TRACE