name: Deploy Sprouty Services

on:
  push:
    branches: [ master ]
    paths:
      - 'gateway-service/**'
      - 'user-service/**'
      - 'plant-service/**'
      - 'sensor-service/**'
      - 'notification-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [gateway-service, user-service, plant-service, sensor-service, notification-service]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes in ${{ matrix.service }}
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^${{ matrix.service }}/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate to Google Cloud
        if: steps.check_changes.outputs.changed == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        if: steps.check_changes.outputs.changed == 'true'
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        if: steps.check_changes.outputs.changed == 'true'
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Build and Push ${{ matrix.service }}
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          docker build -t europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sprouty-repo/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sprouty-repo/${{ matrix.service }}:latest

      - name: Get GKE Credentials
        if: steps.check_changes.outputs.changed == 'true'
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: sprouty-cluster
          location: europe-west4

      - name: Restart K8s Deployment
        if: steps.check_changes.outputs.changed == 'true'
        run: kubectl rollout restart deployment ${{ matrix.service }}